### ISSUE TITLE
Hello, may I ask if the dataset is open source

### ISSUE THREAD

**Issue by ww618** [sam4llis/Predicting-Keystrokes#1]
Hello, may I ask if the dataset is open source

**Comment by sam4llis** [comment]
Hi, apologies for the delay in my response. As the keystroke data is technically private data from participants, I'm unable to share it externally. If I can ask your use case then maybe I can provide some sample of the dataset (without private data) :)

**Comment by ww618** [comment]
> 嗨，很抱歉我的回复延迟。由于击键数据在技术上是参与者的私人数据，因此我无法在外部共享。如果我能问你的用例，那么也许我可以提供一些数据集的样本（没有私有数据）:)

Hi, hello, the data set I asked about is used to help me finish my undergraduate thesis. Can I share some data sets?

**Comment by ww618** [comment]
> > 嗨，很抱歉我的回复延迟。由于击键数据在技术上是参与者的私人数据，因此我无法在外部共享。如果我能问你的用例，那么也许我可以提供一些数据集的样本（没有私有数据）:)
> 
> 嗨，你好，我问的数据集是用来帮助我完成本科论文的。我可以共享一些数据集吗？
I only need a portion of the data to complete my graduation thesis. Thank you for replying to me
