### ISSUE TITLE
Hi, hello, the data set I asked about is used to help me finish my undergraduate thesis. Can I share some data sets?

### ISSUE THREAD

**Issue by ww618** [sam4llis/Predicting-Keystrokes#3]
Hi, hello, the data set I asked about is used to help me finish my undergraduate thesis. Can I share some data sets?

**Comment by sam4llis** [comment]
Hi @ww618 sorry for my late response - I've uploaded the data to this Google Drive link:

https://drive.google.com/drive/folders/1S_yohp4_q_Sb66N8li2HHdNxb-SRTRbm?usp=sharing

This link will expire in 48 hours so please download the dataset to your own machine :)

`CH01` and `CH02` refer to the left and right channels respectively.

**Comment by ww618** [comment]
Hello, there is a JSON file corresponding to WAV in your code. Could you please provide me with this JSON file (CH01, CH02).
I can't run the model with your code. Can you provide a rough documentation to explain it? Thank you
